# Use the official Microsoft .NET SDK image as a build environment
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

# Set the working directory in the container
WORKDIR /app

# Copy the project file and restore any dependencies (via dotnet restore)
COPY ["HMS/HMS.csproj", "./"]
RUN dotnet restore "./HMS.csproj"

# Copy the rest of the application code
COPY . .

# Publish the application to the /app/publish directory
RUN dotnet publish "HMS.csproj" -c Release -o /app/publish

# Use the official Microsoft .NET runtime image as the base for the final image
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 80

# Copy the published app from the build stage to the container
COPY --from=build /app/publish .

# Define the entry point to run the application
ENTRYPOINT ["dotnet", "./publish/HMS.dll"]
